#!/bin/bash

result="$(nvidia-smi --format=csv,noheader --query-gpu=utilization.gpu,temperature.gpu)"
result=($(echo "$result" | sed 's/ //g'))


a=($(echo "$result" | tr ',' '\n'))
echo "${a[0]} ${a[1]}°"